apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: annika
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: nikhilrjn/mysql:1.2
    ports:
    - containerPort: 3306

