kind: Service
apiVersion: v1
metadata:
  name: annikasql-service
  namespace: annika
spec:
  selector:
    name: annikawebsql
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30060
