apiVersion: v1
kind: Pod
metadata:
  name: annikawebsql
  namespace: annika
  labels:
    app: whatsmysecret
    name: annikawebsql
spec:
  containers:
  - name: annika
    image: nikhilrjn/annikasql:1.2
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
