apiVersion: v1
kind: Pod
metadata:
  name: klingons
  namespace: species
spec:
  containers:
  - name: klingons
    image: polinux/stress
    resources:
      limits:
        cpu: 200m
        memory: "500Mi"
      requests:
        cpu: 200m
        memory: "500Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "350M", "--vm-hang", "1"]
