apiVersion: v1
kind: Pod
metadata:
  name: humans
  namespace: species
spec:
  containers:
  - name: humans
    image: polinux/stress
    resources:
      limits:
        cpu: 200m
        memory: "100Mi"
      requests:
        cpu: 200m
        memory: "75Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "25M", "--vm-hang", "1"]
