apiVersion: v1
kind: Pod
metadata:
  name: vulcans
  namespace: species
spec:
  containers:
  - name: vulcans
    image: polinux/stress
    resources:
      limits:
        cpu: 200m
        memory: "75Mi"
      requests:
        cpu: 200m
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "5M", "--vm-hang", "1"]
